server:
  port: 9381
spring:
  application:
    name: rax
  datasource:
    url: jdbc:mysql://rm-wz988oqn7627g91t3so.mysql.rds.aliyuncs.com:3306/zax?useSSL=true&&serverTimezone=GMT%2b8&charset=utf8mb4&parseTime=true&loc=Local
    username: zax
    password: 7788uJmki*
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
      auto-commit: true
      idle-timeout: 600000
      connection-timeout: 30000
      leak-detection-threshold: 60000
      pool-name: Rax
      connection-test-query: SELECT 1
mybatis:
  mapper-locations: classpath:mappers/*.xml
  config-location: classpath:mybatis-config.xml
logging:
  config: classpath:logback.xml
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /api-ui
app:
  mode: dev
  devToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJyb25nYW54aW4iLCJpYXQiOjE3NTUwMDQwMTksImV4cCI6MTc1NTAxOTU3MSwidXNlcklkIjoxfQ.CB7CT8HQDOzf94C3ZHKs7_aaqL9xo2f8reg7cPQhAsA
  defaultPwd: 8008208820
  jwt:
    secret: Jc^T9kN6bvBZH_Q3@PWU
    expiration: 21600